---
passwd:
  users:
    - name: core
      groups:
        - sudo
        - docker
storage:
  files:
    - filesystem: "root"
      path: "/opt/scaleway-coreos-custom-metadata"
      mode: 0750
      contents:
        remote:
          url: "https://github.com/jbonachera/scaleway-coreos-custom-metadata/releases/download/v0.0.6/scaleway-coreos-custom-metadata"
systemd:
  units:
    - name: "coreos-metadata.service"
      dropins:
        - name: "use-script.conf"
          contents: |
            [Service]
            # Empty ExecStart= prevents the previously defined ExecStart from running
            ExecStart=
            ExecStartPre=/opt/scaleway-coreos-custom-metadata
            ExecStart=/usr/bin/update-ssh-keys -u core
    - name: scw-signal-booted.service
      enabled: true
      contents: |
        [Unit]
        Description=Signal successful boot to Scaleway control plane
        Requires=network-online.target coreos-metadata.service
        After=network.target network-online.target coreos-metadata.service
        [Service]
        Type=oneshot
        ExecStart=/usr/bin/curl -s --fail -XPATCH -H 'Content-Type: application/json' http://169.254.42.42/state -d '{"state_detail": "booted"}' -o /dev/null
        [Install]
        WantedBy=basic.target
    - name: consul-agent.service
      enabled: true
      contents: |
        [Unit]
        Description=Consul agent
        Requires=network-online.target coreos-metadata.service
        After=coreos-metadata.service
        [Service]
        Restart=always
        EnvironmentFile=-/run/metadata/coreos
        ExecStart=/usr/bin/docker run --rm --name consul -v /var/lib/consul:/consul/data --net=host consul agent -bind=${COREOS_CUSTOM_PRIVATE_IPV4} -client=0.0.0.0  -retry-join=servers.nomad.discovery.${COREOS_CUSTOM_ZONE_ID}.vx-labs.net
        [Install]
        WantedBy=basic.target
    - name: nomad-agent.service
      enabled: true
      contents: |
        [Unit]
        Description=Run nomad agent
        Requires=network-online.target coreos-metadata.service
        After=coreos-metadata.service
        [Service]
        Restart=always
        EnvironmentFile=-/run/metadata/coreos
        ExecStart=/usr/bin/docker run --name nomad-agent  --net=host --privileged -v /tmp:/tmp -v /var/run/docker.sock:/var/run/docker.sock -v /var/lib/nomad:/var/lib/nomad --rm jbonachera/nomad-agent agent -config=/etc/nomad  -servers servers.nomad.discovery.${COREOS_CUSTOM_ZONE_ID}.vx-labs.net:4647
        [Install]
        WantedBy=basic.target
    - name: linkerd.service
      enabled: true
      contents: |
        [Unit]
        Description=Run linkerd
        Requires=network-online.target coreos-metadata.service
        After=coreos-metadata.service
        [Service]
        Restart=always
        EnvironmentFile=-/run/metadata/coreos
        ExecStart=/usr/bin/docker run --rm --name linked --net=host jbonachera/linkerd
        [Install]
        WantedBy=basic.target

