---
systemd:
  units:
    - name: extract-nomad-token.path
      enabled: true
      contents: |
        [Unit]
        Description=Create a nomad token from instance token
        [Path]
        PathModified=/run/vault/token
        [Install]
        WantedBy=multi-user.target
    - name: extract-nomad-token.service
      contents: |
        [Unit]
        Description=Run nomad server
        Requires=network-online.target
        [Service]
        Type=oneshot
        EnvironmentFile=/run/metadata/coreos
        EnvironmentFile=/etc/userdata.env
        ExecStart=/bin/sh -c '/usr/bin/docker  run --rm  \
          --cap-add=IPC_LOCK \
          --net=host \
          -v /run/vault:/run/vault \
          -e VAULT_ADDR=${VAULT_ADDR} \
          -e VAULT_TOKEN=$(cat /run/vault/token) \
          vault vault token create -ttl 10m -orphan -field 'token' -policy nomad-server -role nomad-server > /run/vault/nomad-token.tmp'
        ExecStart=/bin/mv /run/vault/nomad-token.tmp /run/vault/nomad-token
    - name: nomad.path
      enabled: true
      contents: |
        [Unit]
        Description=Start nomad when token is created
        [Path]
        PathModified=/run/vault/nomad-token
        [Install]
        WantedBy=multi-user.target
    - name: nomad.service
      contents: |
        [Unit]
        Description=Run nomad server
        Requires=network-online.target
        After=extract-nomad-token.service
        [Service]
        EnvironmentFile=/run/metadata/coreos
        EnvironmentFile=/etc/userdata.env
        ExecStart=/bin/sh -c '/usr/bin/docker  run --rm --name nomad-server \
          -e VAULT_TOKEN=$(cat /run/vault/nomad-token) \
          -e VAULT_ADDR=${VAULT_ADDR} \
          -v /var/lib/nomad:/var/lib/nomad \
          --net=host jbonachera/nomad \
            agent -config=/etc/nomad -server \
            -consul-server-auto-join  \
            -consul-auto-advertise \
            -bootstrap-expect=${CLUSTER_SIZE} \
            -vault-enabled \
            -vault-address=${VAULT_ADDR} \
            -vault-create-from-role=${VAULT_TOKEN_ROLE}'
        ExecStop=/usr/bin/docker stop nomad-server
        [Install]
        WantedBy=basic.target