version: '3.3'
services:
  consul:
    image: jbonachera/consul
    environment:
      - SERVICE_NAME=consul
      - MIN_NODES_SIZE=3
      - EMERGENCY_RECOVERY=true
    networks:
      - vault
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: any
  vault:
    image: jbonachera/vault
    environment:
      - DISABLE_MLOCK=true
      - CONSUL_ADDR=http://consul:8500
      - DISABLE_CONSUL_REGISTRATION=1
      - SERVICE_NAME=vault
      - MIN_NODES_SIZE=${CONSUL_NODE_COUNT:-3}
    networks:
      - vault
    deploy:
      mode: replicated
      replicas: 5
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: any
  identity:
    image: vxlabs/identity
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - pki
      - net_pub
      - vault
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: any
      labels:
        traefik.enable: 'true'
        traefik.frontend.rule: Host:identity.cloud.vx-labs.net
        traefik.port: '8009'
        traefik.docker.network: 'net_pub'
    environment:
      - LOG_FORMAT=json
      - LOG_LEVEL=info
      - VAULT_LOG_LEVEL=debug
      - VAULT_DISCOVERY_NAME=tasks.vault
      - CRL_DISTRIBUTION_ROOT=https://identity.cloud.vx-labs.net/v1
      - ORIGIN=*
  front:
    image: vxlabs/vault-admin-console
    networks:
      - front
      - net_pub
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 1s
      restart_policy:
        condition: any
      labels:
        traefik.enable: 'true'
        traefik.frontend.rule: "Host:admin.identity.cloud.vx-labs.net"
        traefik.port: '80'
        traefik.docker.network: 'net_pub'

volumes:
  consul:
networks:
  vault:
  pki:
  front:
  net_pub:
    external: true
