version: '3.3'
services:
  users:
    image: vxlabs/users
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - net_pub
      - users
      - rethinkdb
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: any
      labels:
        traefik.enable: 'true'
        traefik.frontend.entryPoints: https
        traefik.frontend.rule: Host:users.cloud.vx-labs.net
        traefik.port: '8008'
        traefik.docker.network: 'net_pub'
    environment:
      - LOG_FORMAT=json
      - LOG_LEVEL=info
      - APPROLE_ID=591bf3d3-8cd5-22d1-94de-821b5a1e1547
      - APPROLE_SECRET=2d9020eb-66a2-2122-7fbf-dd779ba00ceb
      - RETHINKDB_URL=rethinkdb:28015
      - ORIGIN=*
  services:
    image: vxlabs/services
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - net_pub
      - services
      - rethinkdb
    deploy:
      mode: replicated
      replicas: 1
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: any
      labels:
        traefik.enable: 'true'
        traefik.frontend.entryPoints: https
        traefik.frontend.rule: Host:services.cloud.vx-labs.net
        traefik.port: '8008'
        traefik.docker.network: 'net_pub'
    environment:
      - LOG_FORMAT=json
      - LOG_LEVEL=info
      - APPROLE_ID=c023bb98-de3b-adc0-f0b5-4c2f4f940cd0
      - APPROLE_SECRET=1908d42d-82e3-c774-fad8-9949b18de41c
      - RETHINKDB_URL=rethinkdb:28015
      - ORIGIN=*
  authorization:
    image: vxlabs/authorization
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - net_pub
      - authz
      - rethinkdb
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 5s
      restart_policy:
        condition: any
      labels:
        traefik.enable: 'true'
        traefik.frontend.entryPoints: https
        traefik.frontend.rule: Host:authorization.cloud.vx-labs.net
        traefik.port: '8007'
        traefik.docker.network: 'net_pub'
    environment:
      - LOG_FORMAT=json
      - LOG_LEVEL=info
      - APPROLE_ID=a06ec660-3c7a-3fce-35b6-999e725ce890
      - APPROLE_SECRET=7d647a23-2e33-48c0-edec-b25c39919259
      - RETHINKDB_URL=rethinkdb:28015
      - ORIGIN=*
  rethinkdb:
    image: jbonachera/rethinkdb
    environment:
      - SERVICE_NAME=rethinkdb
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - rethinkdb
      - net_pub
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: any
      labels:
        traefik.enable: 'false'
        traefik.frontend.entryPoints: https
        traefik.frontend.rule: Host:rethink.identity.cloud.vx-labs.net
        traefik.backend.loadbalancer.sticky: 'true'
        traefik.docker.network: 'net_pub'
        traefik.port: '8080'
    volumes:
      - type: volume
        source: rethinkdb
        target: /var/lib/rethinkdb
volumes:
  rethinkdb:
networks:
  rethinkdb:
  authz:
  services:
  users:
  net_pub:
    external: true
