version: '3.3'
services:
  userapi:
    image: vxlabs/iot-userapi
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - iot
      - net_pub
      - rethinkdb
    environment:
      - LOG_FORMAT=json
      - LOG_LEVEL=info
      - API_CLIENT_CACHING=true
      - APPROLE_ID=909380e5-a83f-7100-c9bf-a0e6b3fae8f6
      - APPROLE_SECRET=701269bd-006b-4b02-184e-8ec19e120cde
      - ORIGIN=*
      - RETHINKDB_URL=rethinkdb:28015
      - SIG_TOKEN=thie7quae3oxuBai6ugh
    deploy:
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 1s
      restart_policy:
        condition: any
      labels:
        traefik.enable: 'true'
        traefik.frontend.entryPoints: https
        traefik.frontend.rule: Host:api.iot.cloud.vx-labs.net
        traefik.port: '8006'
        traefik.docker.network: 'net_pub'
  hooks:
    image: vxlabs/iot-mqtt-hooks
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - mqtt
    environment:
      - LOG_FORMAT=json
      - LOG_LEVEL=info
      - APPROLE_ID=0a8523c2-94d0-f29f-b87c-17079be83513
      - APPROLE_SECRET=9f2870ea-3cdc-1c85-1c45-b27ae28c8453
      - ALLOWED_SUBNET=10.0.0.0/24
      - ORIGIN=*
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 1s
      restart_policy:
        condition: any
      labels:
        traefik.enable: 'false'
        traefik.frontend.entryPoints: https
        traefik.frontend.rule: Host:hooks.iot.cloud.vx-labs.net
        traefik.port: '8005'
  login:
    image: vxlabs/iot-login
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - iot
      - net_pub
      - rethinkdb
    environment:
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - APPROLE_ID=fba0c5a8-394a-f804-8219-7cd98fcf3a2c
      - APPROLE_SECRET=fbbc1b99-2d4e-d50d-1ab9-734024e2d214
      - ORIGIN=*
      - RETHINKDB_URL=rethinkdb:28015
      - SIG_TOKEN=thie7quae3oxuBai6ugh
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 1s
      restart_policy:
        condition: any
      labels:
        traefik.enable: 'true'
        traefik.frontend.entryPoints: https
        traefik.frontend.rule: Host:login.iot.cloud.vx-labs.net
        traefik.port: '8007'
        traefik.docker.network: 'net_pub'
  registration:
    image: vxlabs/iot-registration
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 10s
      retries: 3
    networks:
      - iot
      - net_pub
      - rethinkdb
    environment:
      - LOG_LEVEL=info
      - LOG_FORMAT=json
      - APPROLE_ID=70079208-26d1-2106-9a2d-710cd34b205c
      - APPROLE_SECRET=b20fee86-6b6f-0b0f-5c98-aad707532065
      - RETHINKDB_URL=rethinkdb:28015
      - ORIGIN=*
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 1s
      restart_policy:
        condition: any
      labels:
        traefik.enable: 'true'
        traefik.frontend.entryPoints: https
        traefik.frontend.rule: Host:registration.iot.cloud.vx-labs.net
        traefik.port: '8008'
        traefik.docker.network: 'net_pub'
  userfront:
    image: vxlabs/iot-console
    networks:
      - front
      - net_pub
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 1s
      restart_policy:
        condition: any
      labels:
        traefik.enable: 'true'
        traefik.frontend.entryPoints: https
        traefik.frontend.rule: Host:iot.cloud.vx-labs.net
        traefik.docker.network: 'net_pub'
        traefik.port: '80'
  front:
    image: vxlabs/vault-admin-console
    networks:
      - front
      - net_pub
    deploy:
      mode: replicated
      replicas: 3
      update_config:
        parallelism: 1
        delay: 1s
      restart_policy:
        condition: any
      labels:
        traefik.enable: 'true'
        traefik.frontend.entryPoints: https
        traefik.frontend.rule: Host:admin.identity.cloud.vx-labs.net
        traefik.docker.network: 'net_pub'
        traefik.port: '80'
  rethinkdb:
    image: jbonachera/rethinkdb
    environment:
      - SERVICE_NAME=rethinkdb
    networks:
      - rethinkdb
      - net_pub
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 10s
      retries: 3
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 30s
      restart_policy:
        condition: any
      labels:
        traefik.enable: 'false'
        traefik.frontend.entryPoints: https
        traefik.frontend.rule: Host:rethink.cloud.vx-labs.net
        traefik.backend.loadbalancer.sticky: 'true'
        traefik.port: '8080'
        traefik.docker.network: 'net_pub'
    volumes:
      - type: volume
        source: rethinkdb
        target: /var/lib/rethinkdb
  vernemq:
    image: vxlabs/vernemq
    healthcheck:
      test: ["CMD", "true"]
      interval: 5s
      timeout: 10s
      retries: 3
    environment:
      - SERVICE_NAME=vernemq
      - X509_KEYFILE=/run/key.pem
      - X509_CAFILE=/run/ca.pem
      - X509_CERTFILE=/run/cert.pem
      - APPROLE_ID=498c6fb9-d442-3ea6-cb69-d80e4fcc835b
      - APPROLE_SECRET=1cced63a-0330-6368-b29e-110231d05b3d
      - X509_CN=mqtt.iot.cloud.vx-labs.net
      - X509_O=vx-labs.net
      - X509_OU=iot
      - X509_PKI=pki-infra
      - SSL_CA=/run/cert.pem
      - SSL_CERT=/run/cert.pem
      - SSL_KEY=/run/key.pem
      - SSL_AUTH=yes
      - ALLOW_ANONYMOUS=off
      - REGISTER_HOOK_ENDPOINT=http://tasks.hooks:8005/v1/auth_on_register/
      - PUBLISH_HOOK_ENDPOINT=http://tasks.hooks:8005/v1/auth_on_publish/
      - SUBSCRIBE_HOOK_ENDPOINT=http://tasks.hooks:8005/v1/auth_on_subscribe/
    networks:
      - mqtt
      - net_pub
    deploy:
      mode: global
      update_config:
        parallelism: 1
        delay: 60s
      restart_policy:
        condition: any
      labels:
        traefik.enable: 'true'
        traefik.protocol: http
        traefik.frontend.entryPoints: https
        traefik.frontend.rule: Host:mqtt.iot.cloud.vx-labs.net
        traefik.port: '8080'
        traefik.docker.network: 'net_pub'
    ports:
      - target: 8883
        published: 8883
        protocol: tcp
        mode: ingress
      - target: 8080
        published: 8884
        protocol: tcp
        mode: ingress
    volumes:
      - type: volume
        target: /var/lib/vernemq
        volume:
          nocopy: true
volumes:
  rethinkdb:
  consul:
networks:
  pki:
  iot:
  front:
  rethinkdb:
  mqtt:
  net_pub:
    external: true
