---
passwd:
  users:
    - name: core
      groups:
        - sudo
        - docker
systemd:
  units:
    - name: docker.service
      dropins:
        - name: 20-http-proxy.conf
          contents: |
            [Unit]
            After=coreos-metadata.service
            [Service]
            EnvironmentFile=/etc/userdata.env
    - name: "coreos-metadata.service"
      dropins:
        - name: "use-script.conf"
          contents: |
            [Service]
            ExecStart=
            ExecStart=/usr/share/oem/scaleway-coreos-custom-metadata -c COUNT
    - name: "coreos-metadata-sshkeys@.service"
      enabled: true
      dropins:
        - name: "use-script.conf"
          contents: |
            [Service]
            ExecStart=
            ExecStart=/usr/share/oem/scaleway-coreos-custom-metadata ssh-keys %i
    - name: nats.service
      enabled: true
      contents: |
        [Unit]
        Description=Run nats streaming server
        Requires=network-online.target coreos-metadata.service
        After=coreos-metadata.service
        [Service]
        EnvironmentFile=/run/metadata/coreos
        EnvironmentFile=/etc/userdata.env
        ExecStart=/usr/bin/docker  run --rm --name nats \
          -v /var/lib/nats:/var/lib/nats \
          --net=host nats-streaming:0.11.2 \
          --cluster_peers ${NATS_PEERS} \
          --cluster_node_id ${NATS_ID} \
          --routes ${NATS_ROUTES} \
          --cluster nats://0.0.0.0:5222 \
          --cluster_log_path /var/lib/nats/streaming \
          -m 8444 \
          --clustered \
          -st file \
          --dir /var/lib/nats \
          -cid events
        ExecStop=/usr/bin/docker stop nats
        [Install]
        WantedBy=basic.target
