---
systemd:
  units:
    - name: nomad-agent.service
      enabled: true
      contents: |
        [Unit]
        Description=Run nomad agent
        Requires=network-online.target vault-agent.service
        After=vault-agent.service
        [Service]
        EnvironmentFile=/run/metadata/coreos
        EnvironmentFile=/etc/userdata.env
        ExecStartPre=/usr/bin/mkdir -p /var/lib/nomad
        ExecStart=/usr/bin/docker run --rm --privileged --name nomad-agent \
          -v /tmp:/tmp \
          -v /var/run/docker.sock:/var/run/docker.sock \
          --mount type=bind,source=/var/lib/nomad,destination=/var/lib/nomad,bind-propagation=shared \
          --net=host jbonachera/nomad-agent \
            agent -config=/etc/nomad -client \
            -consul-client-auto-join  \
            -consul-auto-advertise \
            -vault-enabled \
            -vault-address=${VAULT_ADDR}
        ExecStop=/usr/bin/docker stop nomad-agent
        [Install]
        WantedBy=basic.target
    - name: linkerd.service
      enabled: true
      contents: |
        [Unit]
        Description=Run linkerd
        Requires=network-online.target coreos-metadata.service
        After=coreos-metadata.service
        [Service]
        Restart=always
        EnvironmentFile=-/run/metadata/coreos
        ExecStart=/usr/bin/docker run --rm --name linkerd --net=host quay.io/jbonachera/linkerd
        ExecStop=/usr/bin/docker stop linkerd
        [Install]
        WantedBy=basic.target

