module "agent-1" {
  source           = "../modules/instance"
  image            = "${element(var.agent_images, 0)}"
  secgroup         = "${scaleway_security_group.nomad_agent.id}"
  hostname         = "nomad-agent-1"
  region           = "${var.region}"
  domain           = "${var.cloudflare_domain}"
  cloudinit        = "${file("config.yaml")}"
  discovery_record = "agents.nomad"
  vault_role       = "nomad-role"
  vault_token_role = "nomad-cluster"
}
module "agent-2" {
  source           = "../modules/instance"
  image            = "${element(var.agent_images, 1)}"
  secgroup         = "${scaleway_security_group.nomad_agent.id}"
  hostname         = "nomad-agent-2"
  region           = "${var.region}"
  domain           = "${var.cloudflare_domain}"
  cloudinit        = "${file("config.yaml")}"
  discovery_record = "agents.nomad"
  vault_role       = "nomad-role"
  vault_token_role = "nomad-cluster"
}
module "agent-3" {
  source           = "../modules/instance"
  image            = "${element(var.agent_images, 2)}"
  secgroup         = "${scaleway_security_group.nomad_agent.id}"
  hostname         = "nomad-agent-3"
  region           = "${var.region}"
  domain           = "${var.cloudflare_domain}"
  cloudinit        = "${file("config.yaml")}"
  discovery_record = "agents.nomad"
  vault_role       = "nomad-role"
  vault_token_role = "nomad-cluster"
}